from constant.enums import LandmarkType, ArchType, ToothType

candidate_definition = {
    ArchType.UPPER.value: {
        ToothType.INCISOR_UR1_LL1.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {}
        },
        ToothType.INCISOR_UL1_LR1.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.INCISOR_UR2_LL2.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-0.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-0.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.INCISOR_UL2_LR2.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-0.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-0.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.CANINE_UR3_LL3.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 1.5],
                'd': [True, True],
                'r': [-4, 4],
                'l': [True, True],
                'f': [-2.1, 2],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 1.5],
                'd': [True, True],
                'r': [-4, 4],
                'l': [True, True],
                'f': [-2.1, 2],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.CANINE_UL3_LR3.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 1.5],
                'd': [True, True],
                'r': [-4, 4],
                'l': [True, True],
                'f': [-2, 2.1],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 1.5],
                'd': [True, True],
                'r': [-4, 4],
                'l': [True, True],
                'f': [-2, 2.1],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.PREMOLAR_UR4_LL4.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            }
        },
        ToothType.PREMOLAR_UL4_LR4.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, +5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, +5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            }
        },
        ToothType.PREMOLAR_UR5_LL5.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            }
        },
        ToothType.PREMOLAR_UL5_LR5.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, +5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, +5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            }
        },
        ToothType.MOLAR_UR6_LL6.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, 1.5],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [0.955, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [True, -1],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [-1.505, True],
                'b': [True, True],
            },
        },
        ToothType.MOLAR_UL6_LR6.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, 5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, 5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [True, 1.5],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [0.955, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, -1],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [-1.505, True],
                'b': [True, True],
            },
        },
        ToothType.MOLAR_UR7_LL7.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, 1.5],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [0.955, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [True, -1],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [-1.505, True],
                'b': [True, True],
            },
        },
        ToothType.MOLAR_UL7_LR7.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, 5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, 5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [True, 1.5],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [0.955, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, -1],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [-1.505, True],
                'b': [True, True],
            },
        },
    },
    ArchType.LOWER.value: {
        ToothType.INCISOR_UR1_LL1.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.INCISOR_UL1_LR1.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.INCISOR_UR2_LL2.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-0.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-0.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.INCISOR_UL2_LR2.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-0.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-0.75, 0.75],
                'd': [True, True],
                'r': [-0.75, 0.75],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.CANINE_UR3_LL3.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 1.5],
                'd': [True, True],
                'r': [-4, 4],
                'l': [True, True],
                'f': [-2.1, 2],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 1.5],
                'd': [True, True],
                'r': [-4, 4],
                'l': [True, True],
                'f': [-2.1, 2],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.CANINE_UL3_LR3.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 1.5],
                'd': [True, True],
                'r': [-4, 4],
                'l': [True, True],
                'f': [-2, 2.1],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 1.5],
                'd': [True, True],
                'r': [-4, 4],
                'l': [True, True],
                'f': [-2, 2.1],
                'b': [True, True],
            },
            LandmarkType.CUSP.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-3, 3],
                'b': [True, True],
            }
        },
        ToothType.PREMOLAR_UR4_LL4.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, True],
                'l': [-1, True],
                'f': [-1, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, True],
                'l': [True, 0.25],
                'f': [True, True],
                'b': [True, True],
            }
        },
        ToothType.PREMOLAR_UL4_LR4.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, +5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, +5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [-1, True],
                'l': [True, True],
                'f': [-1, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0.25],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            }
        },
        ToothType.PREMOLAR_UR5_LL5.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, True],
                'l': [0, True],
                'f': [True, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, True],
                'l': [0, True],
                'f': [1, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, True],
                'l': [True, 0],
                'f': [True, True],
                'b': [True, True],
            }
        },
        ToothType.PREMOLAR_UL5_LR5.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, +5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, +5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [True, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [0, True],
                'l': [True, True],
                'f': [1, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, True],
                'b': [True, True],
            }
        },
        ToothType.MOLAR_UR6_LL6.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_MESIAL.value: {
                'u': [True, 2],
                'd': [True, True],
                'r': [True, True],
                'l': [1, True],
                'f': [True, 1.5],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_DISTAL.value: {
                'u': [True, 2],
                'd': [True, True],
                'r': [True, True],
                'l': [1, True],
                'f': [1.95, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, True],
                'l': [True, 0],
                'f': [True, -1.75],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, True],
                'l': [True, 0],
                'f': [2.45, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_MIDDLE.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, True],
                'l': [True, 0],
                'f': [-1.75, 1.75],
                'b': [True, True],
            },
        },
        ToothType.MOLAR_UL6_LR6.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, 5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, 5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_MESIAL.value: {
                'u': [True, 2],
                'd': [True, True],
                'r': [1, True],
                'l': [True, True],
                'f': [True, 1.5],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_DISTAL.value: {
                'u': [True, 2],
                'd': [True, True],
                'r': [1, True],
                'l': [True, True],
                'f': [1.95, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, -1.75],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [2.45, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_MIDDLE.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [-1.75, 1.75],
                'b': [True, True],
            },
        },
        ToothType.MOLAR_UR7_LL7.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-1.5, 2],
                'd': [True, True],
                'r': [-5, 4],
                'l': [True, True],
                'f': [-2.5, 1.8],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_MESIAL.value: {
                'u': [True, 2],
                'd': [True, True],
                'r': [True, True],
                'l': [1, True],
                'f': [True, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_DISTAL.value: {
                'u': [True, 2],
                'd': [True, True],
                'r': [True, True],
                'l': [1, True],
                'f': [2, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, True],
                'l': [True, 0],
                'f': [True, -1],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, True],
                'l': [True, 0],
                'f': [-0.55, True],
                'b': [True, True],
            },
        },
        ToothType.MOLAR_UL7_LR7.value: {
            LandmarkType.MESIAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.DISTAL.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [True, True],
                'l': [True, True],
                'f': [True, 0],
                'b': [True, True],
            },
            LandmarkType.BUCCAL_OR_LABIAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, 5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.LINGUAL_OR_PALATAL.value: {
                'u': [-2, 1.5],
                'd': [True, True],
                'r': [-4, 5],
                'l': [True, True],
                'f': [-1.8, 2.5],
                'b': [True, True],
            },
            LandmarkType.PIT.value: {
                'u': [True, True],
                'd': [True, True],
                'r': [-1, 1],
                'l': [True, True],
                'f': [-1, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_MESIAL.value: {
                'u': [True, 2],
                'd': [True, True],
                'r': [1, True],
                'l': [True, True],
                'f': [True, 1],
                'b': [True, True],
            },
            LandmarkType.CUSP_IN_DISTAL.value: {
                'u': [True, 2],
                'd': [True, True],
                'r': [1, True],
                'l': [True, True],
                'f': [2, True],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_MESIAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [True, -1],
                'b': [True, True],
            },
            LandmarkType.CUSP_OUT_DISTAL.value: {
                'u': [True, 0],
                'd': [True, True],
                'r': [True, 0],
                'l': [True, True],
                'f': [-0.55, True],
                'b': [True, True],
            },
        },
    }
}
